// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhzvMXLQ7f7hlZE4xtvunm9nc9EUa3WkY',
    appId: '1:1081118442339:web:02bb2154e947024d0e0956',
    messagingSenderId: '1081118442339',
    projectId: 'lomba-1f6a1',
    authDomain: 'lomba-1f6a1.firebaseapp.com',
    databaseURL: 'https://lomba-1f6a1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lomba-1f6a1.firebasestorage.app',
    measurementId: 'G-NEJPYXF1CM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTQXCEKFmGK9d2k7HE2sRSG8ZZY6VljPo',
    appId: '1:1081118442339:android:6bfc1f7431500d890e0956',
    messagingSenderId: '1081118442339',
    projectId: 'lomba-1f6a1',
    databaseURL: 'https://lomba-1f6a1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lomba-1f6a1.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhzvMXLQ7f7hlZE4xtvunm9nc9EUa3WkY',
    appId: '1:1081118442339:web:cea24c5e5444c1110e0956',
    messagingSenderId: '1081118442339',
    projectId: 'lomba-1f6a1',
    authDomain: 'lomba-1f6a1.firebaseapp.com',
    databaseURL: 'https://lomba-1f6a1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'lomba-1f6a1.firebasestorage.app',
    measurementId: 'G-KBSPV0E0QK',
  );
}